dubbo:
  application:
    name: provider-order
    #qos-enable: false
    qos-port: 33332
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos #zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.example.order
  protocol:
    name: dubbo
    port: -1